name: Deployment notifications to Slack

on:
  deployment_status
jobs:
  deployment_status_notifications_to_slack:
    runs-on: ubuntu-latest
    steps:
    - name: Deployment Status Notifications to Slack
      uses: citizenos/github-action-deployment-status-notifier-slack@97aefd5
      with:
        slack-incoming-webhook-url: ${{secrets.SLACK_INCOMING_WEBHOOK_URL}}
